# Generated by Django 4.0.6 on 2022-08-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_alter_feed_create_time_alter_participateitems_user_and_more'),
        ('content', '0036_alter_feed_create_time_and_more'),
    ]

    operations = [
    ]
